#!/bin/bash

# Verifica si hay al menos un argumento
if [ $# -lt 1 ]; then
  echo "Uso: $0 <primer_argumento> [otros_argumentos...]"
  exit 1
fi

# Ejecuta el comando pasando todos los argumentos excepto el primero
/opt/lampp/bin/php artisan "${@:1}"
